import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "wia",
  description: "Generated by women in annimation",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <ClerkProvider>
        <body className={"scroll-smooth mx-auto" + inter.className}>
          <Header />
          <div className="mt-28">{children}</div>
          <Footer />
          <ScrollToTopButton/>
        </body>
      </ClerkProvider>
      {/* <script
        type="text/javascript"
        src="../node_modules/tw-elements/dist/js/tw-elements.umd.min.js"
      ></script> */}
    </html>
  );
}
